["Treasures of the dead - Common Config!"]
	#For big adventures you can set this parameter to your distance of view. (if the value of this parameter is higher than your distance of view, than buried treasures and skeletons will spawning in bedrock)
	# Default: 8
	# Range: 6 ~ 128
	randomAdventureItemDistanceInChunks = 8
	#(For servers) For now you can use only ru_ru or en_us
	captain_names_lang = "en_us"
	#ALL BELOW IS NOT WORKING FOR NOW!
	pirateSkeletonHealth = 26.0
	pirateSkeletonDamage = 3.0
	captainSkeletonHealth = 60.0
	captainSkeletonDamage = 4.0
